# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_plotter.ui'
#
# Created: Mon May 18 16:54:55 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WindowPlotter(object):
    def setupUi(self, WindowPlotter):
        WindowPlotter.setObjectName("WindowPlotter")
        WindowPlotter.resize(800, 512)
        self.centralwidget = QtWidgets.QWidget(WindowPlotter)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.FormulaLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.FormulaLineEdit.setObjectName("FormulaLineEdit")
        self.horizontalLayout.addWidget(self.FormulaLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.viewport_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewport_widget.sizePolicy().hasHeightForWidth())
        self.viewport_widget.setSizePolicy(sizePolicy)
        self.viewport_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.viewport_widget.setObjectName("viewport_widget")
        self.verticalLayout.addWidget(self.viewport_widget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.XMinDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.XMinDoubleSpinBox.setDecimals(1)
        self.XMinDoubleSpinBox.setMinimum(-100.0)
        self.XMinDoubleSpinBox.setProperty("value", -5.0)
        self.XMinDoubleSpinBox.setObjectName("XMinDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.XMinDoubleSpinBox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.YMinDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.YMinDoubleSpinBox.setDecimals(1)
        self.YMinDoubleSpinBox.setMinimum(-100.0)
        self.YMinDoubleSpinBox.setProperty("value", -5.0)
        self.YMinDoubleSpinBox.setObjectName("YMinDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.YMinDoubleSpinBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.XMaxDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.XMaxDoubleSpinBox.setDecimals(1)
        self.XMaxDoubleSpinBox.setMinimum(-100.0)
        self.XMaxDoubleSpinBox.setProperty("value", 5.0)
        self.XMaxDoubleSpinBox.setObjectName("XMaxDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.XMaxDoubleSpinBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.YMaxDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.YMaxDoubleSpinBox.setDecimals(1)
        self.YMaxDoubleSpinBox.setMinimum(-100.0)
        self.YMaxDoubleSpinBox.setProperty("value", 5.0)
        self.YMaxDoubleSpinBox.setObjectName("YMaxDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.YMaxDoubleSpinBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.ResolutionSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.ResolutionSpinBox.setMinimum(0.1)
        self.ResolutionSpinBox.setMaximum(100.0)
        self.ResolutionSpinBox.setSingleStep(0.1)
        self.ResolutionSpinBox.setProperty("value", 0.5)
        self.ResolutionSpinBox.setObjectName("ResolutionSpinBox")
        self.horizontalLayout_2.addWidget(self.ResolutionSpinBox)
        self.horizontalLayout_3.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        WindowPlotter.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowPlotter)
        QtCore.QMetaObject.connectSlotsByName(WindowPlotter)

    def retranslateUi(self, WindowPlotter):
        _translate = QtCore.QCoreApplication.translate
        WindowPlotter.setWindowTitle(_translate("WindowPlotter", "Qt integration sample"))
        self.label_6.setText(_translate("WindowPlotter", "Function:"))
        self.FormulaLineEdit.setText(_translate("WindowPlotter", "sin(x) * cos(y) * sin(time.time())"))
        self.groupBox.setTitle(_translate("WindowPlotter", "Output"))
        self.label.setText(_translate("WindowPlotter", "X min:"))
        self.label_2.setText(_translate("WindowPlotter", "Y min:"))
        self.label_3.setText(_translate("WindowPlotter", "X max:"))
        self.label_4.setText(_translate("WindowPlotter", "Y max:"))
        self.label_5.setText(_translate("WindowPlotter", "Resolution:"))

